# Generated by Django 3.2.4 on 2021-07-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_auto_20210723_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Обращение с животными',
                'verbose_name_plural': 'Обращение с животными',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Лечение', 'verbose_name_plural': 'Лечение'},
        ),
        migrations.AddField(
            model_name='skilllist',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.veterinarian', verbose_name='Обращение с животными'),
        ),
    ]
