# Generated by Django 3.2.4 on 2021-07-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_auto_20210723_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценка',
            },
            bases=('skill.baseskill',),
        ),
        migrations.CreateModel(
            name='SecretSigns',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
                ('special', models.CharField(choices=[('Бродяги', 'Бродяги'), ('Воры', 'Воры'), ('Охотники', 'Охотники'), ('Разведчики', 'Разведчики'), ('Серый орден', 'Серый орден'), ('Гильдия', 'Гильдия')], default=0, max_length=25, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Тайные знаки',
                'verbose_name_plural': 'Тайные знаки',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.grade', verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='secretSigns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.secretsigns', verbose_name='Тайные знаки'),
        ),
    ]
