# Generated by Django 3.2.4 on 2021-07-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_auto_20210723_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilllist',
            options={'verbose_name': 'Набор профессиональных навыков', 'verbose_name_plural': 'Наборы профессиональных навыков'},
        ),
        migrations.RemoveField(
            model_name='skilllist',
            name='gamble',
        ),
        migrations.RemoveField(
            model_name='skilllist',
            name='outdoorSurvival',
        ),
        migrations.AlterField(
            model_name='skilllist',
            name='name_list',
            field=models.CharField(default='Профессиональные навыки', max_length=20, verbose_name='Название набора'),
        ),
        migrations.CreateModel(
            name='OtherSkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(default='Общие навыки', max_length=20, verbose_name='Название набора')),
                ('gamble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.gamble', verbose_name='Азартные игры')),
                ('outdoorSurvival', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.outdoorsurvival', verbose_name='Выживание')),
            ],
            options={
                'verbose_name': 'Набор общих навыков',
                'verbose_name_plural': 'Наборы общих навыков',
            },
        ),
    ]
