# Generated by Django 3.2.4 on 2021-07-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_auto_20210723_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertain',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
                ('special', models.CharField(choices=[('Актерство', 'Актерство'), ('Комедия', 'Комедия'), ('Пение', 'Пение'), ('Сказительство', 'Сказительство')], default=0, max_length=25, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Артистизм',
                'verbose_name_plural': 'Артистизм',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AddField(
            model_name='otherskilllist',
            name='entertain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.entertain', verbose_name='Артистизм'),
        ),
    ]
