# Generated by Django 3.2.4 on 2021-07-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_auto_20210723_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bribery',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Подкуп',
                'verbose_name_plural': 'Подкуп',
            },
            bases=('skill.baseskill',),
        ),
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Обаяние',
                'verbose_name_plural': 'Обаяние',
            },
            bases=('skill.baseskill',),
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Лидерство',
                'verbose_name_plural': 'Лидерство',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AddField(
            model_name='otherskilllist',
            name='bribery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.bribery', verbose_name='Подкуп'),
        ),
        migrations.AddField(
            model_name='otherskilllist',
            name='leadership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.leadership', verbose_name='Лидерство'),
        ),
        migrations.AddField(
            model_name='otherskilllist',
            name='сharm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.charm', verbose_name='Обаяние'),
        ),
    ]
