# Generated by Django 3.2.4 on 2021-07-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_auto_20210723_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gossip',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Сплетничество',
                'verbose_name_plural': 'Сплетничество',
            },
            bases=('skill.baseskill',),
        ),
        migrations.RenameField(
            model_name='otherskilllist',
            old_name='сharm',
            new_name='charm',
        ),
        migrations.AddField(
            model_name='otherskilllist',
            name='gossip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.gossip', verbose_name='Сплетничество'),
        ),
    ]
