# Generated by Django 3.2.4 on 2021-07-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalskilllist',
            name='prayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.prayer', verbose_name='Молитвословие'),
        ),
    ]
