# Generated by Django 3.2.4 on 2021-07-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0016_professionalskilllist_prayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseskill',
            name='isActive',
        ),
    ]
