# Generated by Django 3.2.4 on 2021-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0020_alter_otherskilllist_name_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskilllist',
            name='name_list',
            field=models.CharField(default='Профессиональные навыки', max_length=60, verbose_name='Название набора'),
        ),
    ]
