# Generated by Django 3.2.4 on 2021-06-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Карие', max_length=20, verbose_name='Цвет глаз')),
                ('description', models.TextField(blank=True, verbose_name='Описание глаз')),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Коричнивые', max_length=20, verbose_name='Цвет волос')),
                ('description', models.TextField(blank=True, verbose_name='Описание прически')),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('gold', 'Золотое'), ('silver', 'Серебряное'), ('cuprum', 'Медное')], max_length=6, verbose_name='Сословие')),
                ('description', models.TextField(blank=True, verbose_name='Описание сословия')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nation', models.CharField(default='Человек', max_length=20, verbose_name='Народ персонажа')),
                ('description', models.TextField(blank=True, verbose_name='Описание народа')),
            ],
        ),
        migrations.CreateModel(
            name='NumberMetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2, verbose_name='Положение в сословии')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Men', 'Мужчина'), ('Women', 'Женщина')], max_length=5, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание статуса')),
                ('metal', models.ForeignKey(default='cuprum', on_delete=django.db.models.deletion.CASCADE, to='character.metal')),
                ('number', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='character.numbermetal')),
            ],
        ),
    ]
