# Generated by Django 3.2.4 on 2021-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(default='33', max_length=4, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(default='174', max_length=4, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='Рик', max_length=20, verbose_name='Имя'),
        ),
    ]
