# Generated by Django 3.2.4 on 2021-06-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20210630_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_career', models.CharField(max_length=35, verbose_name='Название карьеры')),
                ('description', models.TextField(blank=True, verbose_name='Описание карьеры')),
            ],
            options={
                'verbose_name': 'Карьера',
                'verbose_name_plural': 'Карьеры',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=15, verbose_name='Название класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_species', models.CharField(max_length=40, verbose_name='Название ступени карьеры (должность)')),
                ('step', models.CharField(max_length=2, verbose_name='Порядковый номер ступени')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.career', verbose_name='Карьера')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='SetArchiveSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_species', models.ManyToManyField(to='character.Species', verbose_name='Предыдущие должности')),
            ],
            options={
                'verbose_name': 'Набор архивных должностей',
                'verbose_name_plural': 'Наборы архивных должностей',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='name_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.class', verbose_name='Название класса'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.species', verbose_name='Текущая должность'),
        ),
    ]
