# Generated by Django 3.2.4 on 2021-06-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20210630_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attribute', models.CharField(max_length=20, verbose_name='Название атрибута')),
                ('description', models.TextField(blank=True, verbose_name='Описание атрибута')),
                ('start', models.CharField(max_length=3, verbose_name='Начальное значение')),
                ('steps', models.CharField(blank=True, max_length=3, verbose_name='Сделанные шаги')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.ManyToManyField(blank=True, to='character.Species', verbose_name='Должности'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(max_length=30, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
                ('start', models.CharField(max_length=3, verbose_name='Начальное значение')),
                ('steps', models.CharField(blank=True, max_length=3, verbose_name='Сделанные шаги')),
                ('is_other', models.BooleanField(default=False, verbose_name='Является общим навыком?')),
                ('base_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.attribute', verbose_name='Базовый атрибут')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='SetAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_set_attribute', models.CharField(blank=True, max_length=30, verbose_name='Название набора атрибутов')),
                ('attributes', models.ManyToManyField(to='character.Attribute', verbose_name='Набор атрибутов')),
            ],
            options={
                'verbose_name': 'Набор атрибутов',
                'verbose_name_plural': 'Набор атрибутов',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='set_attributes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.setattributes', verbose_name='Набор атрибутов'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(null=True, to='character.Skill', verbose_name='Навыки'),
        ),
    ]
