# Generated by Django 3.2.4 on 2021-07-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20210630_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attribute', models.CharField(max_length=20, verbose_name='Название характеристики')),
                ('description', models.TextField(blank=True, verbose_name='Описание характеристики')),
            ],
            options={
                'verbose_name': 'Название характеристики',
                'verbose_name_plural': 'Название характеристики',
            },
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='setattributes',
            options={'verbose_name': 'Набор характеристик', 'verbose_name_plural': 'Набор характеристик'},
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='description',
        ),
        migrations.AlterField(
            model_name='setattributes',
            name='attributes',
            field=models.ManyToManyField(to='character.Attribute', verbose_name='Набор характеристик'),
        ),
        migrations.AlterField(
            model_name='setattributes',
            name='name_set_attribute',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название набора характеристик'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='base_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.attribute', verbose_name='Базовая характеристика'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.nameattribute', verbose_name='Название характеристики'),
        ),
    ]
