# Generated by Django 3.2.4 on 2021-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_career_available_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание класса'),
        ),
    ]
