# Generated by Django 3.2.4 on 2021-07-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_career_available_talents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_estate', models.CharField(choices=[('Золотое', 'Золотое'), ('Медное', 'Медное'), ('Серебренное', 'Серебренное')], max_length=30, verbose_name='Сословие')),
                ('rank', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2, verbose_name='Положение в сословии')),
            ],
            options={
                'verbose_name': 'Сословие',
                'verbose_name_plural': 'Сословия',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nation', models.CharField(choices=[('Человек', 'Человек'), ('Полурослик', 'Полурослик'), ('Гном', 'Гном'), ('Высший эльф', 'Высший эльф'), ('Лесной эльф', 'Лесной эльф')], max_length=30, verbose_name='Народ')),
            ],
            options={
                'verbose_name': 'Народ',
                'verbose_name_plural': 'Народы',
            },
        ),
        migrations.AlterField(
            model_name='career',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.estate', verbose_name='Сословие и положение'),
        ),
        migrations.AlterField(
            model_name='class',
            name='available_nation',
            field=models.ManyToManyField(blank=True, to='career.Nation', verbose_name='Перечень доступных народов'),
        ),
    ]
