# Generated by Django 3.2.4 on 2021-07-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20210724_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListArchiveCarriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ManyToManyField(blank=True, to='career.Career', verbose_name='Список должностей')),
            ],
            options={
                'verbose_name': 'Список должностей',
                'verbose_name_plural': 'Списки должностей',
            },
        ),
    ]
