# Generated by Django 3.2.4 on 2021-07-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.IntegerField(default=0, verbose_name='Начальное значение')),
                ('numbers_of_steps', models.IntegerField(default=0, verbose_name='Количество сделанных шагов')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSkill',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Ближний бой',
                'verbose_name_plural': 'Ближний бой',
            },
            bases=('character2.baseattribute',),
        ),
    ]
