# Generated by Django 3.2.4 on 2021-07-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseattribute',
            name='numbers_of_steps',
        ),
    ]
