# Generated by Django 3.2.4 on 2021-07-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character2', '0002_remove_baseattribute_numbers_of_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agility',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Проворство',
                'verbose_name_plural': 'Проворство',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='BallisticSkill',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Дальний бой',
                'verbose_name_plural': 'Дальний бой',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Dexterity',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Ловкость',
                'verbose_name_plural': 'Ловкость',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Харизма',
                'verbose_name_plural': 'Харизма',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Инициатива',
                'verbose_name_plural': 'Инициатива',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Интеллект',
                'verbose_name_plural': 'Интеллект',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Сила',
                'verbose_name_plural': 'Сила',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Toughness',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Выносливость',
                'verbose_name_plural': 'Выносливость',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.CreateModel(
            name='Willpower',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character2.baseattribute')),
            ],
            options={
                'verbose_name': 'Сила воли',
                'verbose_name_plural': 'Сила воли',
            },
            bases=('character2.baseattribute',),
        ),
        migrations.AddField(
            model_name='baseattribute',
            name='numbers_of_steps',
            field=models.IntegerField(default=0, verbose_name='Количество шагов'),
        ),
    ]
