# Generated by Django 3.2.4 on 2021-07-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0013_alter_baseattribute_initial_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_estate', models.CharField(choices=[('Золотое', 'Золотое'), ('Медное', 'Медное'), ('Серебренное', 'Серебренное')], max_length=30, verbose_name='Сословие')),
                ('rank', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2, verbose_name='Положение в сословии')),
            ],
            options={
                'verbose_name': 'Сословие',
                'verbose_name_plural': 'Сословия',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nation', models.CharField(choices=[('Человек', 'Человек'), ('Полурослик', 'Полурослик'), ('Гном', 'Гном'), ('Высший эльф', 'Высший эльф'), ('Лесной эльф', 'Лесной эльф')], max_length=30, verbose_name='Народ')),
            ],
            options={
                'verbose_name': 'Народ',
                'verbose_name_plural': 'Народы',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Джон', max_length=30, verbose_name='Имя персонажа')),
                ('add_weaponSkill', models.CharField(default='0', max_length=3, verbose_name='Шаги в Ближний бой')),
                ('add_ballisticSkill', models.CharField(default='0', max_length=3, verbose_name='Шаги в Дальний бой')),
                ('add_strength', models.CharField(default='0', max_length=3, verbose_name='Шаги в Сила')),
                ('add_toughness', models.CharField(default='0', max_length=3, verbose_name='Шаги в Выносливость')),
                ('add_initiative', models.CharField(default='0', max_length=3, verbose_name='Шаги в Инициатива')),
                ('add_agility', models.CharField(default='0', max_length=3, verbose_name='Шаги в Проворство')),
                ('add_dexterity', models.CharField(default='0', max_length=3, verbose_name='Шаги в Ловкость')),
                ('add_intelligence', models.CharField(default='0', max_length=3, verbose_name='Шаги в Интеллект')),
                ('add_willpower', models.CharField(default='0', max_length=3, verbose_name='Шаги в Сила воли')),
                ('add_fellowship', models.CharField(default='0', max_length=3, verbose_name='Шаги в Харизма')),
                ('other_skills', models.CharField(max_length=3)),
                ('pro_skills', models.CharField(max_length=3)),
                ('estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.estate', verbose_name='Статус')),
                ('init_attribute', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.attributelist', verbose_name='Начальные значения характеристик')),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nation', verbose_name='Народ')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
    ]
