# Generated by Django 3.2.4 on 2021-07-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(default='Стандарт', max_length=20, verbose_name='Название набора')),
            ],
            options={
                'verbose_name': 'Набор характеристик',
                'verbose_name_plural': 'Наборы характеристик',
            },
        ),
        migrations.CreateModel(
            name='BaseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_meaning', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], default='0', max_length=3, verbose_name='Начальное значение')),
            ],
        ),
        migrations.CreateModel(
            name='BaseSkillOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(blank=True, choices=[('Азартные игры', 'Азартные игры'), ('Атлетика', 'Атлетика'), ('Артистизм (Актерство)', 'Артистизм (Актерство)'), ('Артистизм (Комедия)', 'Артистизм (Комедия)'), ('Артистизм (Пение)', 'Артистизм (Пение)'), ('Артистизм (Сказительство)', 'Артистизм (Сказительство)'), ('Верховая езда (Гигантские волки)', 'Верховая езда (Гигантские волки)'), ('Верховая езда (Грифоны)', 'Верховая езда (Грифоны)'), ('Верховая езда (Демигрифы)', 'Верховая езда (Демигрифы)'), ('Верховая езда (Лошади)', 'Верховая езда (Лошади)'), ('Верховая езда (Пегасы)', 'Верховая езда (Пегасы)'), ('Вождение', 'Вождение'), ('Выживание', 'Выживание'), ('Гребля', 'Гребля'), ('Запугивание', 'Запугивание'), ('Интуиция', 'Интуиция'), ('Искусство (Гравюра)', 'Искусство (Гравюра)'), ('Искусство (Живопись)', 'Искусство (Живопись)'), ('Искусство (Картография)', 'Искусство (Картография)'), ('Искусство (Мозаика)', 'Искусство (Мозаика)'), ('Искусство (Скульптура)', 'Искусство (Скульптура)'), ('Искусство (Татуировка)', 'Искусство (Татуировка)'), ('Искусство (Ткачество)', 'Искусство (Ткачество)'), ('Кутеж', 'Кутеж'), ('Лазанье', 'Лазанье'), ('Лидерство', 'Лидерство'), ('Наблюдательность', 'Наблюдательность'), ('Обаяние', 'Обаяние'), ('Ориентирование', 'Ориентирование'), ('Подкуп', 'Подкуп'), ('Рукопашный бой (Основное)', 'Рукопашный бой (Основное)'), ('Рукопашный бой (Двуручное)', 'Рукопашный бой (Двуручное)'), ('Рукопашный бой (Древковое)', 'Рукопашный бой (Древковое)'), ('Рукопашный бой (Кавалерийское)', 'Рукопашный бой (Кавалерийское)'), ('Рукопашный бой (Кулачное)', 'Рукопашный бой (Кулачное)'), ('Рукопашный бой (Парирующее)', 'Рукопашный бой (Парирующее)'), ('Рукопашный бой (Фехтовальное)', 'Рукопашный бой (Фехтовальное)'), ('Рукопашный бой (Цепы)', 'Рукопашный бой (Цепы)'), ('Скрытность (Города)', 'Скрытность (Города)'), ('Скрытность (Дикая природа)', 'Скрытность (Дикая природа)'), ('Скрытность (Подземелья)', 'Скрытность (Подземелья)'), ('Сплетничество', 'Сплетничество'), ('Стойкость', 'Стойкость'), ('Торговля', 'Торговля'), ('Уклонение', 'Уклонение'), ('Усмирение животных', 'Усмирение животных'), ('Хладнокровие', 'Хладнокровие')], max_length=50, null=True, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
            ],
            options={
                'verbose_name': 'Общий навык абстрактный',
                'verbose_name_plural': 'Общие навыки абстрактные',
            },
        ),
        migrations.CreateModel(
            name='BaseSkillPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_skill', models.CharField(blank=True, choices=[('Взлом', 'Взлом'), ('Выслеживание', 'Выслеживание'), ('Дрессировка (Голуби)', 'Дрессировка (Голуби)'), ('Дрессировка (Демигрифы)', 'Дрессировка (Демигрифы)'), ('Дрессировка (Лошади)', 'Дрессировка (Лошади)'), ('Дрессировка (Пегасы)', 'Дрессировка (Пегасы)'), ('Дрессировка (Собаки)', 'Дрессировка (Собаки)'), ('Знание (Геология)', 'Знание (Геология)'), ('Знание (Геральдика)', 'Знание (Геральдика)'), ('Знание (Закон)', 'Знание (Закон)'), ('Знание (Инженерное дело)', 'Знание (Инженерное дело)'), ('Знание (История)', 'Знание (История)'), ('Знание (Магия)', 'Знание (Магия)'), ('Знание (Металлургия)', 'Знание (Металлургия)'), ('Знание (Наука)', 'Знание (Наука)'), ('Знание (Теология)', 'Знание (Теология)'), ('Книжные изыскания', 'Книжные изыскания'), ('Концентрация (Азир)', 'Концентрация (Азир)'), ('Концентрация (Акши)', 'Концентрация (Акши)'), ('Концентрация (Гайран)', 'Концентрация (Гайран)'), ('Концентрация (Гарр)', 'Концентрация (Гарр)'), ('Концентрация (Дхар)', 'Концентрация (Дхар)'), ('Концентрация (Улгу)', 'Концентрация (Улгу)'), ('Концентрация (Шамон)', 'Концентрация (Шамон)'), ('Концентрация (Хиш)', 'Концентрация (Хиш)'), ('Концентрация (Шаиш)', 'Концентрация (Шаиш)'), ('Лечение', 'Лечение'), ('Ловкость рук', 'Ловкость рук'), ('Молитвословие', 'Молитвословие'), ('Музицирование (Волынка)', 'Музицирование (Волынка)'), ('Музицирование (Клавесин)', 'Музицирование (Клавесин)'), ('Музицирование (Лютня)', 'Музицирование (Лютня)'), ('Музицирование (Рожок)', 'Музицирование (Рожок)'), ('Музицирование (Скрипка)', 'Музицирование (Скрипка)'), ('Обращение с животными', 'Обращение с животными'), ('Обращение с ловушками', 'Обращение с ловушками'), ('Оценка', 'Оценка'), ('Плавание', 'Плавание'), ('Ремесло (Аптекарь)', 'Ремесло (Аптекарь)'), ('Ремесло (Бальзамировщик)', 'Ремесло (Бальзамировщик)'), ('Ремесло (Дубильщик)', 'Ремесло (Дубильщик)'), ('Ремесло (Каллиграф)', 'Ремесло (Каллиграф)'), ('Ремесло (Кузнец)', 'Ремесло (Кузнец)'), ('Ремесло (Плотник)', 'Ремесло (Плотник)'), ('Ремесло (Повар)', 'Ремесло (Повар)'), ('Ремесло (Свечник)', 'Ремесло (Свечник)'), ('Стрельба (Арбалеты)', 'Стрельба (Арбалеты)'), ('Стрельба (Взрывчатка)', 'Стрельба (Взрывчатка)'), ('Стрельба (Инженерное)', 'Стрельба (Инженерное)'), ('Стрельба (Ловчее)', 'Стрельба (Ловчее)'), ('Стрельба (Луки)', 'Стрельба (Луки)'), ('Стрельба (Метательное)', 'Стрельба (Метательное)'), ('Стрельба (Пороховое)', 'Стрельба (Пороховое)'), ('Стрельба (Пращи)', 'Стрельба (Пращи)'), ('Сценическое искусство (Акробатика)', 'Сценическое искусство (Акробатика)'), ('Сценическое искусство (Глотание огня)', 'Сценическое искусство (Глотание огня)'), ('Сценическое искусство (Жонглирование)', 'Сценическое искусство (Жонглирование)'), ('Сценическое искусство (Клоунада)', 'Сценическое искусство (Клоунада)'), ('Сценическое искусство (Пантомима)', 'Сценическое искусство (Пантомима)'), ('Сценическое искусство (Танец)', 'Сценическое искусство (Танец)'), ('Сценическое искусство (Хождение по канату)', 'Сценическое искусство (Хождение по канату)'), ('Тайные знаки (Бродяги)', 'Тайные знаки (Бродяги)'), ('Тайные знаки (Воры)', 'Тайные знаки (Воры)'), ('Тайные знаки (Гильдия)', 'Тайные знаки (Гильдия)'), ('Тайные знаки (Охотники)', 'Тайные знаки (Охотники)'), ('Тайные знаки (Разведчики)', 'Тайные знаки (Разведчики)'), ('Тайные знаки (Серый орден)', 'Тайные знаки (Серый орден)'), ('Хождение под парусом (Баржи)', 'Хождение под парусом (Баржи)'), ('Хождение под парусом (Волчьи корабли)', 'Хождение под парусом (Волчьи корабли)'), ('Хождение под парусом (Каравеллы)', 'Хождение под парусом (Каравеллы)'), ('Хождение под парусом (Когги)', 'Хождение под парусом (Когги)'), ('Хождение под парусом (Лодки)', 'Хождение под парусом (Лодки)'), ('Хождение под парусом (Фрегаты)', 'Хождение под парусом (Фрегаты)'), ('Язык (Боевой арго)', 'Язык (Боевой арго)'), ('Язык (Бретонский)', 'Язык (Бретонский)'), ('Язык (Воровской арго)', 'Язык (Воровской арго)'), ('Язык (Гильдейский арго)', 'Язык (Гильдейский арго)'), ('Язык (Классический)', 'Язык (Классический)'), ('Язык (Кхазалид)', 'Язык (Кхазалид)'), ('Язык (Магический)', 'Язык (Магический)'), ('Язык (Тилейский)', 'Язык (Тилейский)')], max_length=50, null=True, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
            ],
            options={
                'verbose_name': 'Профессиональный навык абстрактный',
                'verbose_name_plural': 'Профессиональные навыки абстрактные',
            },
        ),
        migrations.CreateModel(
            name='BaseTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название таланта')),
                ('max', models.CharField(blank=True, max_length=100, verbose_name='Максимальный уровень таланта')),
                ('description', models.TextField(blank=True, verbose_name='Описание таланта')),
            ],
            options={
                'verbose_name': 'Талант абстрактный',
                'verbose_name_plural': 'Таланты абстрактные',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_career', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('rank_career', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='Ступень карьеры')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Джон', max_length=30, verbose_name='Имя персонажа')),
                ('age', models.CharField(blank=True, max_length=4, null=True, verbose_name='Возраст')),
                ('height', models.CharField(blank=True, max_length=4, null=True, verbose_name='Рост')),
                ('hair', models.CharField(blank=True, max_length=20, null=True, verbose_name='Волосы')),
                ('fate', models.CharField(blank=True, max_length=3, null=True, verbose_name='Судьба')),
                ('fortune', models.CharField(blank=True, max_length=3, null=True, verbose_name='Удача')),
                ('resilience', models.CharField(blank=True, max_length=3, null=True, verbose_name='Упорство')),
                ('resolve', models.CharField(blank=True, max_length=3, null=True, verbose_name='Решимость')),
                ('motivation', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мотивация')),
                ('exp_current', models.CharField(blank=True, max_length=5, null=True, verbose_name='Запас опыта')),
                ('exp_spent', models.CharField(blank=True, max_length=5, null=True, verbose_name='Портаченый опыт')),
                ('short_ambition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткосрочная амбиция')),
                ('long_ambition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгосрочная амбиция')),
                ('add_weaponSkill', models.CharField(default='0', max_length=3, verbose_name='Шаги в Ближний бой')),
                ('add_ballisticSkill', models.CharField(default='0', max_length=3, verbose_name='Шаги в Дальний бой')),
                ('add_strength', models.CharField(default='0', max_length=3, verbose_name='Шаги в Сила')),
                ('add_toughness', models.CharField(default='0', max_length=3, verbose_name='Шаги в Выносливость')),
                ('add_initiative', models.CharField(default='0', max_length=3, verbose_name='Шаги в Инициатива')),
                ('add_agility', models.CharField(default='0', max_length=3, verbose_name='Шаги в Проворство')),
                ('add_dexterity', models.CharField(default='0', max_length=3, verbose_name='Шаги в Ловкость')),
                ('add_intelligence', models.CharField(default='0', max_length=3, verbose_name='Шаги в Интеллект')),
                ('add_willpower', models.CharField(default='0', max_length=3, verbose_name='Шаги в Сила воли')),
                ('add_fellowship', models.CharField(default='0', max_length=3, verbose_name='Шаги в Харизма')),
                ('penny', models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество пенни')),
                ('corruption', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пункты скверны')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_estate', models.CharField(choices=[('Золотое', 'Золотое'), ('Медное', 'Медное'), ('Серебренное', 'Серебренное')], max_length=30, verbose_name='Сословие')),
                ('rank', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2, verbose_name='Положение в сословии')),
            ],
            options={
                'verbose_name': 'Сословие',
                'verbose_name_plural': 'Сословия',
            },
        ),
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет глаз')),
                ('description', models.CharField(blank=True, max_length=60, null=True, verbose_name='Описание глаз')),
            ],
            options={
                'verbose_name': 'Глаза',
                'verbose_name_plural': 'Глаза',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(blank=True, max_length=3, null=True, verbose_name='Скорость')),
                ('walk', models.CharField(blank=True, max_length=3, null=True, verbose_name='Скорость шагом (ярдов за ход)')),
                ('run', models.CharField(blank=True, max_length=3, null=True, verbose_name='Скорость бегом (ярдов за ход)')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещение',
            },
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('effect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эффект')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Расширенное описание')),
            ],
            options={
                'verbose_name': 'Мутация',
                'verbose_name_plural': 'Мутации',
            },
        ),
        migrations.CreateModel(
            name='NameAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attr', models.CharField(blank=True, choices=[('Ближний бой', 'Ближний бой'), ('Дальний бой', 'Дальний бой'), ('Сила', 'Сила'), ('Выносливость', 'Выносливость'), ('Инициатива', 'Инициатива'), ('Проворство', 'Проворство'), ('Ловкость', 'Ловкость'), ('Интеллект', 'Интеллект'), ('Сила воли', 'Сила воли'), ('Харизма', 'Харизма')], max_length=30, verbose_name='Характеристика')),
                ('description', models.TextField(blank=True, verbose_name='Описание характеристики')),
            ],
            options={
                'verbose_name': 'Название характеристики',
                'verbose_name_plural': 'Названия характеристик',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nation', models.CharField(choices=[('Человек', 'Человек'), ('Полурослик', 'Полурослик'), ('Гном', 'Гном'), ('Высший эльф', 'Высший эльф'), ('Лесной эльф', 'Лесной эльф')], max_length=30, verbose_name='Народ')),
            ],
            options={
                'verbose_name': 'Народ',
                'verbose_name_plural': 'Народы',
            },
        ),
        migrations.CreateModel(
            name='Psychology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Психическая особенность',
                'verbose_name_plural': 'Психические особенности',
            },
        ),
        migrations.CreateModel(
            name='Agility',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Проворство',
                'verbose_name_plural': 'Проворство',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='BallisticSkill',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Дальний бой',
                'verbose_name_plural': 'Дальний бой',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Dexterity',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Ловкость',
                'verbose_name_plural': 'Ловкость',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Харизма',
                'verbose_name_plural': 'Харизма',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Инициатива',
                'verbose_name_plural': 'Инициатива',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Интеллект',
                'verbose_name_plural': 'Интеллект',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Сила',
                'verbose_name_plural': 'Сила',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Toughness',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Выносливость',
                'verbose_name_plural': 'Выносливость',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='WeaponSkill',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Ближний бой',
                'verbose_name_plural': 'Ближний бой',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Willpower',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baseList.baseattribute')),
            ],
            options={
                'verbose_name': 'Сила воли',
                'verbose_name_plural': 'Сила воли',
            },
            bases=('baseList.baseattribute',),
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], max_length=3, null=True, verbose_name='Уровень развития')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.basetalent', verbose_name='Талант')),
            ],
            options={
                'verbose_name': 'Талант персонажа',
                'verbose_name_plural': 'Таланты персонажа',
            },
        ),
        migrations.CreateModel(
            name='SkillPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], default='0', max_length=3, verbose_name='Шаги развития')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.baseskillpro', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Профессиональный навык персонажа',
                'verbose_name_plural': 'Профессиональные навыки персонажа',
            },
        ),
        migrations.CreateModel(
            name='SkillOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], default='0', max_length=3, null=True, verbose_name='Шаги развития')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.baseskillother', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Общий навык персонажа',
                'verbose_name_plural': 'Общие навыки персонажа',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_party', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название команды')),
                ('short_ambition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткосрочная амбиция')),
                ('long_ambition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгосрочная амбиция')),
                ('description', models.TextField(blank=True, verbose_name='Расширенное описание группы')),
                ('members', models.ManyToManyField(blank=True, to='baseList.Character', verbose_name='Список участников')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='ListProSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название листа навыков')),
                ('skill', models.ManyToManyField(blank=True, to='baseList.SkillPro', verbose_name='Профессиональный навык')),
            ],
            options={
                'verbose_name': 'Лист профессиональных навыков',
                'verbose_name_plural': 'Листы профессиональных навыков',
            },
        ),
        migrations.CreateModel(
            name='ListOtherSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название листа навыков')),
                ('skill', models.ManyToManyField(blank=True, to='baseList.SkillOther', verbose_name='Общий навык')),
            ],
            options={
                'verbose_name': 'Лист общих навыков',
                'verbose_name_plural': 'Листы общих навыков',
            },
        ),
        migrations.CreateModel(
            name='ListArchiveCarriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ManyToManyField(blank=True, to='baseList.Career', verbose_name='Список должностей')),
            ],
            options={
                'verbose_name': 'Список должностей',
                'verbose_name_plural': 'Списки должностей',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание класса')),
                ('available_nation', models.ManyToManyField(blank=True, to='baseList.Nation', verbose_name='Перечень доступных народов')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класс',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='archive_career',
            field=models.ManyToManyField(blank=True, to='baseList.ListArchiveCarriers', verbose_name='Ранние должности'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.career', verbose_name='Текущая должность'),
        ),
        migrations.AddField(
            model_name='character',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.estate', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.eyes', verbose_name='Глаза'),
        ),
        migrations.AddField(
            model_name='character',
            name='init_attribute',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.attributelist', verbose_name='Начальные значения характеристик'),
        ),
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.movement', verbose_name='Скорость'),
        ),
        migrations.AddField(
            model_name='character',
            name='mutation',
            field=models.ManyToManyField(blank=True, to='baseList.Mutation', verbose_name='Психика'),
        ),
        migrations.AddField(
            model_name='character',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nation', verbose_name='Народ'),
        ),
        migrations.AddField(
            model_name='character',
            name='other_skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.listotherskills', verbose_name='Лист общих навыков'),
        ),
        migrations.AddField(
            model_name='character',
            name='pro_skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.listproskills', verbose_name='Лист профессиональных навыков'),
        ),
        migrations.AddField(
            model_name='character',
            name='psy',
            field=models.ManyToManyField(blank=True, to='baseList.Psychology', verbose_name='Психика'),
        ),
        migrations.AddField(
            model_name='character',
            name='talents',
            field=models.ManyToManyField(blank=True, to='baseList.Talent', verbose_name='Таланты'),
        ),
        migrations.AddField(
            model_name='career',
            name='available_attr',
            field=models.ManyToManyField(blank=True, to='baseList.NameAttr', verbose_name='Доступные характеристики'),
        ),
        migrations.AddField(
            model_name='career',
            name='available_skills',
            field=models.ManyToManyField(blank=True, to='baseList.BaseSkillPro', verbose_name='Доступные навыки'),
        ),
        migrations.AddField(
            model_name='career',
            name='available_talents',
            field=models.ManyToManyField(blank=True, to='baseList.BaseTalent', verbose_name='Доступные таланты'),
        ),
        migrations.AddField(
            model_name='career',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.estate', verbose_name='Сословие и положение'),
        ),
        migrations.AddField(
            model_name='career',
            name='name_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.class', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='basetalent',
            name='depend_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nameattr', verbose_name='Связанная характеристика'),
        ),
        migrations.AddField(
            model_name='basetalent',
            name='depend_skill_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.baseskillother', verbose_name='Бонус на проверку общего навыка'),
        ),
        migrations.AddField(
            model_name='basetalent',
            name='depend_skill_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.baseskillpro', verbose_name='Бонус на проверку профессионального навыка'),
        ),
        migrations.AddField(
            model_name='baseskillpro',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nameattr', verbose_name='Базовая характеристика'),
        ),
        migrations.AddField(
            model_name='baseskillother',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nameattr', verbose_name='Базовая характеристика'),
        ),
        migrations.AddField(
            model_name='baseattribute',
            name='name_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nameattr', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='agility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.agility', verbose_name='Проворство'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='ballisticSkill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.ballisticskill', verbose_name='Дальний бой'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='dexterity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.dexterity', verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='fellowship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.fellowship', verbose_name='Харизма'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.initiative', verbose_name='Инициатива'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='intelligence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.intelligence', verbose_name='Интеллект'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.strength', verbose_name='Сила'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='toughness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.toughness', verbose_name='Выносливость'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='weaponSkill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.weaponskill', verbose_name='Ближний бой'),
        ),
        migrations.AddField(
            model_name='attributelist',
            name='willpower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseList.willpower', verbose_name='Сила воли'),
        ),
    ]
