# Generated by Django 3.2.4 on 2021-07-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0001_initial'),
        ('baseList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='other_skills',
        ),
        migrations.AddField(
            model_name='character',
            name='other_skills',
            field=models.ManyToManyField(to='skill2.SkillOther'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='pro_skills',
        ),
        migrations.AddField(
            model_name='character',
            name='pro_skills',
            field=models.ManyToManyField(to='skill2.SkillPro'),
        ),
    ]
