# Generated by Django 3.2.4 on 2021-07-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0009_remove_attributelist_name'),
        ('baseList', '0002_remove_character_weaponskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='add_agility',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Проворство'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_ballisticSkill',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Дальний бой'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_dexterity',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Ловкость'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_fellowship',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Харизма'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_initiative',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Инициатива'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_intelligence',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Интеллект'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_strength',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Сила'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_toughness',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Выносливость'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_weaponSkill',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Ближний бой'),
        ),
        migrations.AddField(
            model_name='character',
            name='add_willpower',
            field=models.CharField(default='0', max_length=3, verbose_name='Шаги в Сила воли'),
        ),
        migrations.AddField(
            model_name='character',
            name='init_attribute',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='attribute.attributelist', verbose_name='Начальные значения характеристик'),
        ),
    ]
