# Generated by Django 3.2.4 on 2021-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0001_initial'),
        ('baseList', '0002_auto_20210724_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='other_skills',
            field=models.ManyToManyField(blank=True, to='skill2.SkillOther', verbose_name='Общие навыки'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pro_skills',
            field=models.ManyToManyField(blank=True, to='skill2.SkillPro', verbose_name='Профессиональные навыки'),
        ),
    ]
