# Generated by Django 3.2.4 on 2021-07-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0017_remove_baseskill_isactive'),
        ('baseList', '0004_auto_20210724_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='other_skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.otherskilllist', verbose_name='Шаги в общих навыках'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pro_skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.professionalskilllist', verbose_name='Шаги в профессиональных навыках'),
        ),
    ]
