# Generated by Django 3.2.4 on 2021-07-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0006_auto_20210724_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.nation', verbose_name='Народ'),
        ),
    ]
