# Generated by Django 3.2.4 on 2021-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0007_alter_character_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_estate', models.CharField(choices=[('Золотое', 'Золотое'), ('Медное', 'Медное'), ('Серебренное', 'Серебренное')], max_length=30, verbose_name='Сословие')),
                ('rank', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=2, verbose_name='Положение в сословии')),
            ],
            options={
                'verbose_name': 'Сословие',
                'verbose_name_plural': 'Сословия',
            },
        ),
    ]
