# Generated by Django 3.2.4 on 2021-07-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20210724_2133'),
        ('baseList', '0009_alter_character_talents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.estate', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='character',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.nation', verbose_name='Народ'),
        ),
        migrations.DeleteModel(
            name='Estate',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
    ]
