# Generated by Django 3.2.4 on 2021-07-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20210724_2133'),
        ('baseList', '0010_auto_20210724_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.career', verbose_name='Текущая должность'),
        ),
    ]
