# Generated by Django 3.2.4 on 2021-07-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_listarchivecarriers'),
        ('baseList', '0012_character_archive_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет глаз')),
                ('description', models.CharField(blank=True, max_length=60, null=True, verbose_name='Описание глаз')),
            ],
            options={
                'verbose_name': 'Глаза',
                'verbose_name_plural': 'Глаза',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Волосы'),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='character',
            name='archive_career',
            field=models.ManyToManyField(blank=True, to='career.ListArchiveCarriers', verbose_name='Ранние должности'),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.eyes', verbose_name='Глаза'),
        ),
    ]
