# Generated by Django 3.2.4 on 2021-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0013_auto_20210725_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fate',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Судьба'),
        ),
        migrations.AddField(
            model_name='character',
            name='fortune',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Удача'),
        ),
        migrations.AddField(
            model_name='character',
            name='motivation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Мотивация'),
        ),
        migrations.AddField(
            model_name='character',
            name='resilience',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Упорство'),
        ),
        migrations.AddField(
            model_name='character',
            name='resolve',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Решимость'),
        ),
    ]
