# Generated by Django 3.2.4 on 2021-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0014_auto_20210725_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp_current',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Запас опыта'),
        ),
        migrations.AddField(
            model_name='character',
            name='exp_spent',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Портаченый опыт'),
        ),
        migrations.AddField(
            model_name='character',
            name='long_ambition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгосрочная амбиция'),
        ),
        migrations.AddField(
            model_name='character',
            name='short_ambition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткосрочная амбиция'),
        ),
    ]
