# Generated by Django 3.2.4 on 2021-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0015_auto_20210725_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_party', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название команды')),
                ('short_ambition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткосрочная амбиция')),
                ('long_ambition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгосрочная амбиция')),
                ('description', models.TextField(blank=True, verbose_name='Расширенное описание группы')),
                ('members', models.ManyToManyField(blank=True, to='baseList.Character', verbose_name='Список участников')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
    ]
