# Generated by Django 3.2.4 on 2021-07-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0016_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(blank=True, max_length=3, null=True, verbose_name='Скорость')),
                ('walk', models.CharField(blank=True, max_length=3, null=True, verbose_name='Скорость шагом (ярдов за ход)')),
                ('run', models.CharField(blank=True, max_length=3, null=True, verbose_name='Скорость бегом (ярдов за ход)')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещение',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.movement', verbose_name='Скорость'),
        ),
    ]
