# Generated by Django 3.2.4 on 2021-07-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0012_auto_20210724_2126'),
        ('baseList', '0017_auto_20210725_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='character',
            name='other_skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.listotherskills', verbose_name='Лист общих навыков'),
        ),
    ]
