# Generated by Django 3.2.4 on 2021-07-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0012_auto_20210724_2126'),
        ('baseList', '0018_auto_20210725_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='pro_skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.listproskills', verbose_name='Лист профессиональных навыков'),
        ),
    ]
