# Generated by Django 3.2.4 on 2021-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0019_alter_character_pro_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание глаз')),
            ],
            options={
                'verbose_name': 'Психическая особенность',
                'verbose_name_plural': 'Психические особенности',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='penny',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество пенни'),
        ),
        migrations.AddField(
            model_name='character',
            name='psy',
            field=models.ManyToManyField(to='baseList.Psychology', verbose_name='Психика'),
        ),
    ]
