# Generated by Django 3.2.4 on 2021-07-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0020_auto_20210725_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='psy',
            field=models.ManyToManyField(blank=True, to='baseList.Psychology', verbose_name='Психика'),
        ),
        migrations.AlterField(
            model_name='psychology',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
