# Generated by Django 3.2.4 on 2021-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0021_auto_20210725_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('effect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Эффект')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Расширенное описание')),
            ],
            options={
                'verbose_name': 'Психическая особенность',
                'verbose_name_plural': 'Психические особенности',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='corruption',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Пункты скверны'),
        ),
        migrations.AddField(
            model_name='character',
            name='mutation',
            field=models.ManyToManyField(blank=True, to='baseList.Mutation', verbose_name='Психика'),
        ),
    ]
