# Generated by Django 3.2.4 on 2021-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0022_auto_20210725_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
