# Generated by Django 3.2.4 on 2021-07-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0023_wizard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutation',
            options={'verbose_name': 'Мутация', 'verbose_name_plural': 'Мутации'},
        ),
    ]
