# Generated by Django 3.2.4 on 2021-07-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0008_estate'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='available_nation',
            field=models.ManyToManyField(blank=True, null=True, to='baseList.Nation', verbose_name='Перечень доступных народов'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_class',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название класса'),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_career', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('name_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
    ]
