# Generated by Django 3.2.4 on 2021-07-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseList', '0007_alter_character_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='Народ')),
                ('available_nation', models.ManyToManyField(to='baseList.Nation')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класс',
            },
        ),
    ]
