# Generated by Django 3.2.4 on 2021-07-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseList', '0007_auto_20210724_1935'),
        ('attribute', '0014_auto_20210724_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название класса')),
                ('available_nation', models.ManyToManyField(blank=True, to='baseList.Nation', verbose_name='Перечень доступных народов')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класс',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_career', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('rank_career', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='Ступень карьеры')),
                ('available_attr', models.ManyToManyField(blank=True, to='attribute.NameAttr', verbose_name='Доступные характеристики')),
                ('estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseList.estate', verbose_name='Сословие и положение')),
                ('name_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
    ]
