# Generated by Django 3.2.4 on 2021-07-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0009_auto_20210724_2028'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='available_skills',
            field=models.ManyToManyField(blank=True, to='skill2.BaseSkillPro', verbose_name='Доступные навыки'),
        ),
    ]
