# Generated by Django 3.2.4 on 2021-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseList', '0009_character_estate'),
        ('career', '0003_career_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='available_nation',
            field=models.ManyToManyField(blank=True, to='baseList.Nation', verbose_name='Перечень доступных народов'),
        ),
    ]
