# Generated by Django 3.2.4 on 2021-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0011_talent'),
        ('career', '0003_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='available_talents',
            field=models.ManyToManyField(blank=True, to='skill2.Talent', verbose_name='Доступные таланты'),
        ),
    ]
