# Generated by Django 3.2.4 on 2021-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0012_auto_20210724_2126'),
        ('career', '0004_career_available_talents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='available_talents',
            field=models.ManyToManyField(blank=True, to='skill2.BaseTalent', verbose_name='Доступные таланты'),
        ),
    ]
