# Generated by Django 3.2.4 on 2021-06-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_talent', models.CharField(max_length=30, verbose_name='Название таланта')),
                ('description', models.TextField(blank=True, verbose_name='Описание таланта')),
                ('max_rank', models.CharField(blank=True, max_length=100, verbose_name='Максимальный уровень таланта')),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
            },
        ),
        migrations.AlterModelOptions(
            name='eyes',
            options={'verbose_name': 'Глаза', 'verbose_name_plural': 'Глаза'},
        ),
        migrations.AlterModelOptions(
            name='hair',
            options={'verbose_name': 'Волосы', 'verbose_name_plural': 'Волосы'},
        ),
        migrations.AlterModelOptions(
            name='metal',
            options={'verbose_name': 'Сословие', 'verbose_name_plural': 'Сословия'},
        ),
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name': 'Народ', 'verbose_name_plural': 'Народы'},
        ),
        migrations.AlterModelOptions(
            name='numbermetal',
            options={'verbose_name': 'Положение в сословии', 'verbose_name_plural': 'Положение в сословии'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Пол'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='metal',
            name='metal',
            field=models.CharField(choices=[('Золотое', 'Золотое'), ('Серебряное', 'Серебряное'), ('Медное', 'Медное')], max_length=10, verbose_name='Сословие'),
        ),
        migrations.CreateModel(
            name='CurrentTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(default='1', max_length=3, verbose_name='Уровень таланта')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.talent', verbose_name='Талант')),
            ],
            options={
                'verbose_name': 'Талант и его текущий уровень',
                'verbose_name_plural': 'Талант и его текущий уровень',
            },
        ),
    ]
