# Generated by Django 3.2.4 on 2021-06-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20210630_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.eyes', verbose_name='Глаза')),
                ('hair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.hair', verbose_name='Волосы')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.nation', verbose_name='Народ')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.sex', verbose_name='Пол')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.status', verbose_name='Статус персонажа')),
                ('talents', models.ManyToManyField(to='character.CurrentTalent', verbose_name='Таланты')),
            ],
        ),
    ]
