# Generated by Django 3.2.4 on 2021-07-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20210722_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='set_attributes',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='base_attribute',
        ),
        migrations.AddField(
            model_name='character',
            name='attributes',
            field=models.ManyToManyField(to='character.Attribute', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='nameskill',
            name='base_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character.nameattribute', verbose_name='Базовая характеристика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='character.Skill', verbose_name='Навыки'),
        ),
    ]
