# Generated by Django 3.2.4 on 2021-07-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='0', max_length=3, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Шаги развития',
                'verbose_name_plural': 'Шаги развития',
            },
        ),
        migrations.CreateModel(
            name='WeaponSkill',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Ближний бой',
                'verbose_name_plural': 'Ближний бой',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.AddField(
            model_name='baseattribute',
            name='numbers_of_steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.step', verbose_name='Количество шагов развития'),
        ),
    ]
