# Generated by Django 3.2.4 on 2021-07-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseattribute',
            name='numbers_of_steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.step', verbose_name='Количество шагов развития'),
        ),
    ]
