# Generated by Django 3.2.4 on 2021-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_alter_baseattribute_numbers_of_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseattribute',
            name='initial_meaning',
            field=models.CharField(default='0', max_length=3, verbose_name='Начальное значение'),
        ),
    ]
