# Generated by Django 3.2.4 on 2021-07-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_baseattribute_initial_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallisticSkill',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Дальний бой',
                'verbose_name_plural': 'Дальний бой',
            },
            bases=('attribute.baseattribute',),
        ),
    ]
