# Generated by Django 3.2.4 on 2021-07-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0006_baseattribute_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agility',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Проворство',
                'verbose_name_plural': 'Проворство',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Dexterity',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Ловкость',
                'verbose_name_plural': 'Ловкость',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Харизма',
                'verbose_name_plural': 'Харизма',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Инициатива',
                'verbose_name_plural': 'Инициатива',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Интеллект',
                'verbose_name_plural': 'Интеллект',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Сила',
                'verbose_name_plural': 'Сила',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Toughness',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Выносливость',
                'verbose_name_plural': 'Выносливость',
            },
            bases=('attribute.baseattribute',),
        ),
        migrations.CreateModel(
            name='Willpower',
            fields=[
                ('baseattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attribute.baseattribute')),
            ],
            options={
                'verbose_name': 'Сила воли',
                'verbose_name_plural': 'Сила воли',
            },
            bases=('attribute.baseattribute',),
        ),
    ]
