# Generated by Django 3.2.4 on 2021-07-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0008_attributelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributelist',
            name='name',
        ),
    ]
