# Generated by Django 3.2.4 on 2021-07-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0010_attributelist_name_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseattribute',
            name='description',
        ),
    ]
