# Generated by Django 3.2.4 on 2021-07-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0011_remove_baseattribute_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
