# Generated by Django 3.2.4 on 2021-07-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0013_alter_baseattribute_initial_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attr', models.CharField(blank=True, choices=[('Ближний бой', 'Ближний бой'), ('Дальний бой', 'Дальний бой'), ('Сила', 'Сила'), ('Выносливость', 'Выносливость'), ('Инициатива', 'Инициатива'), ('Проворство', 'Проворство'), ('Ловкость', 'Ловкость'), ('Интеллект', 'Интеллект'), ('Сила воли', 'Сила воли'), ('Харизма', 'Харизма')], max_length=30, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AddField(
            model_name='baseattribute',
            name='name_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.nameattr', verbose_name='Характеристика'),
        ),
    ]
