# Generated by Django 3.2.4 on 2021-07-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0014_auto_20210724_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameattr',
            options={'verbose_name': 'Название характеристики', 'verbose_name_plural': 'Названия характеристик'},
        ),
    ]
