# Generated by Django 3.2.4 on 2021-07-24 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0008_auto_20210724_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillpro',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='skillpro',
            name='name_skill',
        ),
        migrations.AddField(
            model_name='skillpro',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.baseskillpro', verbose_name='Навык'),
        ),
    ]
