# Generated by Django 3.2.4 on 2021-07-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0009_auto_20210724_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseskillother',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание навыка'),
        ),
        migrations.AddField(
            model_name='baseskillpro',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание навыка'),
        ),
    ]
