# Generated by Django 3.2.4 on 2021-07-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0016_nameattr_description'),
        ('skill2', '0010_auto_20210724_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название таланта')),
                ('max', models.CharField(blank=True, max_length=100, verbose_name='Максимальный уровень таланта')),
                ('description', models.TextField(blank=True, verbose_name='Описание таланта')),
                ('depend_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.nameattr', verbose_name='Связанная характеристика')),
                ('depend_skill_other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.baseskillother', verbose_name='Бонус на проверку общего навыка')),
                ('depend_skill_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.baseskillpro', verbose_name='Бонус на проверку профессионального навыка')),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
            },
        ),
    ]
