# Generated by Django 3.2.4 on 2021-07-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0016_nameattr_description'),
        ('skill2', '0011_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='depend_attr',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='depend_skill_other',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='depend_skill_pro',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='max',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='name',
        ),
        migrations.AddField(
            model_name='talent',
            name='lvl',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99'), ('100', '100')], max_length=3, null=True, verbose_name='Уровень развития'),
        ),
        migrations.CreateModel(
            name='BaseTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Название таланта')),
                ('max', models.CharField(blank=True, max_length=100, verbose_name='Максимальный уровень таланта')),
                ('description', models.TextField(blank=True, verbose_name='Описание таланта')),
                ('depend_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.nameattr', verbose_name='Связанная характеристика')),
                ('depend_skill_other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.baseskillother', verbose_name='Бонус на проверку общего навыка')),
                ('depend_skill_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.baseskillpro', verbose_name='Бонус на проверку профессионального навыка')),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
            },
        ),
        migrations.AddField(
            model_name='talent',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill2.basetalent', verbose_name='Талант'),
        ),
    ]
