# Generated by Django 3.2.4 on 2021-07-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill2', '0012_auto_20210724_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetalent',
            options={'verbose_name': 'Талант абстрактный', 'verbose_name_plural': 'Таланты абстрактные'},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'verbose_name': 'Талант персонажа', 'verbose_name_plural': 'Таланты персонажа'},
        ),
    ]
