# Generated by Django 3.2.4 on 2021-07-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активен?')),
                ('steps', models.CharField(default='0', max_length=3, verbose_name='Шаги развития')),
            ],
        ),
        migrations.CreateModel(
            name='Gamble',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Азартные игры',
                'verbose_name_plural': 'Азартные игры',
            },
            bases=('skill.baseskill',),
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(default='Стандарт', max_length=20, verbose_name='Название набора')),
                ('gamble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.gamble', verbose_name='Азартные игры')),
            ],
            options={
                'verbose_name': 'Набор навыков',
                'verbose_name_plural': 'Наборы навыков',
            },
        ),
    ]
