# Generated by Django 3.2.4 on 2021-07-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutdoorSurvival',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Выживание',
                'verbose_name_plural': 'Выживание',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='outdoorSurvival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.outdoorsurvival', verbose_name='Выживание'),
        ),
    ]
