# Generated by Django 3.2.4 on 2021-07-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20210723_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Знания',
                'verbose_name_plural': 'Знания',
            },
            bases=('skill.baseskill',),
        ),
        migrations.CreateModel(
            name='TrainingOfAnimals',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Дрессировка',
                'verbose_name_plural': 'Дрессировка',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AlterField(
            model_name='skilllist',
            name='outdoorSurvival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.outdoorsurvival', verbose_name='Выживание'),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='trainingOfAnimals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.trainingofanimals', verbose_name='Дрессировка'),
        ),
    ]
