# Generated by Django 3.2.4 on 2021-07-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20210723_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllist',
            name='outdoorSurvival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.outdoorsurvival', verbose_name='Выживание'),
        ),
    ]
