# Generated by Django 3.2.4 on 2021-07-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_alter_skilllist_outdoorsurvival'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExquisites',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Книжные изыскания',
                'verbose_name_plural': 'Книжные изыскания',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='special',
            field=models.CharField(choices=[('Геология', 'Геология'), ('Геральдика', 'Геральдика'), ('Закон', 'Закон'), ('Инженерное дело', 'Инженерное дело'), ('История', 'История'), ('Магия', 'Магия'), ('Металлургия', 'Металлургия'), ('Наука', 'Наука'), ('Теология', 'Теология')], default=0, max_length=25, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.knowledge', verbose_name='Знания'),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='bookExquisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.bookexquisites', verbose_name='Книжные изыскания'),
        ),
    ]
