# Generated by Django 3.2.4 on 2021-07-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_auto_20210723_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Лечение',
                'verbose_name_plural': 'Книжные изыскания',
            },
            bases=('skill.baseskill',),
        ),
        migrations.RenameModel(
            old_name='BookExquisites',
            new_name='BookSearches',
        ),
        migrations.RenameField(
            model_name='skilllist',
            old_name='bookExquisites',
            new_name='bookSearches',
        ),
        migrations.AddField(
            model_name='trainingofanimals',
            name='special',
            field=models.CharField(choices=[('Голуби', 'Голуби'), ('Демигрифы', 'Демигрифы'), ('Лошади', 'Лошади'), ('Пегасы', 'Пегасы'), ('Собаки', 'Собаки')], default=0, max_length=25, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='skilllist',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.treatment', verbose_name='Лечение'),
        ),
    ]
