# Generated by Django 3.2.4 on 2021-07-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_auto_20210723_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
                ('special', models.CharField(choices=[('Боевой арго', 'Боевой арго'), ('Бретонский', 'Бретонский'), ('Воровской арго', 'Воровской арго'), ('Гильдейский арго', 'Гильдейский арго'), ('Классический', 'Классический'), ('Кхазалид', 'Кхазалид'), ('Магический', 'Магический'), ('Тилейский', 'Тилейский')], default=0, max_length=25, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Язык',
            },
            bases=('skill.baseskill',),
        ),
        migrations.CreateModel(
            name='ProfessionalSkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(default='Профессиональные навыки', max_length=20, verbose_name='Название набора')),
                ('bookSearches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.booksearches', verbose_name='Книжные изыскания')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.grade', verbose_name='Оценка')),
                ('knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.knowledge', verbose_name='Знания')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.language', verbose_name='Язык')),
                ('secretSigns', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.secretsigns', verbose_name='Тайные знаки')),
                ('trainingOfAnimals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.trainingofanimals', verbose_name='Дрессировка')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.treatment', verbose_name='Лечение')),
                ('veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.veterinarian', verbose_name='Обращение с животными')),
            ],
            options={
                'verbose_name': 'Набор профессиональных навыков',
                'verbose_name_plural': 'Наборы профессиональных навыков',
            },
        ),
        migrations.DeleteModel(
            name='SkillList',
        ),
    ]
