# Generated by Django 3.2.4 on 2021-07-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0013_auto_20210723_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haggle',
            fields=[
                ('baseskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skill.baseskill')),
            ],
            options={
                'verbose_name': 'Торговля',
                'verbose_name_plural': 'Торговля',
            },
            bases=('skill.baseskill',),
        ),
        migrations.AddField(
            model_name='otherskilllist',
            name='haggle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.haggle', verbose_name='Торговля'),
        ),
    ]
