# Generated by Django 3.2.4 on 2021-07-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0017_remove_baseskill_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseskill',
            name='steps',
        ),
    ]
