# Generated by Django 3.2.4 on 2021-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0019_baseskill_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskilllist',
            name='name_list',
            field=models.CharField(default='Общие навыки', max_length=60, verbose_name='Название набора'),
        ),
    ]
