# Generated by Django 3.2.4 on 2021-07-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0021_alter_professionalskilllist_name_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskilllist',
            name='gamble',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='skill.gamble', verbose_name='Азартные игры'),
        ),
    ]
