# Generated by Django 3.2.4 on 2021-07-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0022_alter_otherskilllist_gamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherskilllist',
            name='gamble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skill.gamble', verbose_name='Азартные игры'),
        ),
    ]
